modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0"

[[mods]]
modId = "oracle_index"
version = "${version}"
displayName = "Oracle Index"
authors = "Me! - Rearth"
description = '''
Multiplatform Wiki / Documentation mod for content from moddedmc.wiki
'''
#logoFile = ""

[[dependencies.oracle_index]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oracle_index]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.oracle_index]]
modId = "architectury"
type = "required"
versionRange = "[20.0.9,)"
ordering = "AFTER"
side = "BOTH"
